user:
  maximum_name: 50
  maximum_email: 255
  minimum_password_length: 6
  gravatar_size: 50
  per_page: 10
  reset_sent_time: 2
  seed_record: 99
  gravatar_size: 50
microposts:
  maximum_content_length: 140
  seed_record: 50
  user_taked: 6
  sentence: 5
  max_picture_size: 5
  etx_images_accept: "image/jpeg,image/gif,image/png"
pictures:
  resize_to_limit_width: 400
  resize_to_limit_height: 400
