user:
  maximum_name: 50
  maximum_email: 255
  minimum_password_length: 6
  gravatar_size: 50
  per_page: 10
  reset_sent_time: 2
  seed_record: 99
  gravatar_size: 50
  gravatar_follow_size: 30
microposts:
  maximum_content_length: 140
  seed_record: 50
  user_taked: 6
  sentence: 5
  max_picture_size: 5
  etx_images_accept: "image/jpeg,image/gif,image/png"
  per_page: 10
pictures:
  resize_to_limit_width: 400
  resize_to_limit_height: 400
follow:
  min_following: 2
  max_following: 50
  min_followers: 3
  max_followers: 40
  per_page: 8
